# Generated by Django 2.0.6 on 2018-06-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inframanagement', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='power_sources',
            field=models.ManyToManyField(blank=True, to='Inframanagement.Ups'),
        ),
    ]
