# Generated by Django 2.0.6 on 2018-06-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inframanagement', '0003_auto_20180604_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='power_sources',
        ),
        migrations.AddField(
            model_name='location',
            name='power_sources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inframanagement.Ups'),
        ),
    ]
