# Generated by Django 2.0.6 on 2018-06-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inframanagement', '0004_auto_20180604_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='power_sources',
        ),
        migrations.AddField(
            model_name='location',
            name='power_sources',
            field=models.ManyToManyField(blank=True, to='Inframanagement.Ups'),
        ),
    ]
