# Generated by Django 2.0.6 on 2018-06-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inframanagement', '0006_rack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='power_sources',
        ),
        migrations.AddField(
            model_name='ups',
            name='Office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inframanagement.Location'),
        ),
    ]
