# Generated by Django 2.0.6 on 2018-06-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inframanagement', '0007_auto_20180604_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgnization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inframanagement.Orgnization'),
        ),
    ]
