# Generated by Django 2.0.6 on 2018-06-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inframanagement', '0008_auto_20180604_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='powersource',
            name='Office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inframanagement.Location'),
        ),
        migrations.AddField(
            model_name='rack',
            name='PowerSource',
            field=models.ManyToManyField(blank=True, null=True, to='Inframanagement.Ups'),
        ),
    ]
